### ISSUE TITLE
SchemaPlus::Indexes break AR index expressions

### ISSUE THREAD

**Issue by dark-panda** [SchemaPlus/schema_plus_indexes#11]
ActiveRecord 5 added the ability to use functional/expression indexes with PostgreSQ, i.e.

```ruby
t.index 'lower(name)'
```

SchemaPlus::Indexes appears to break this functionality and requires you to fall back to the old-style `execute` statements directly. SchemaPlus::Indexes raises a `PG::UndefinedColumn` exception, with the error message reading `ERROR:  column "lower(name)" does not exist`, as it tries to simply escape the full expression as text rather than allowing the expression through to create the index.

**Comment by urkle** [comment]
this is actually an issue with schema_plus_core.  Which a new version was released that fixes this. Update to schema_plus_core 2.2.1 and this will work again.
